# Generated by Django 5.0.3 on 2024-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='student_directory_path'),
        ),
    ]
