# Generated by Django 5.0.3 on 2024-03-25 07:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_student_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.student_directory_path),
        ),
    ]
